import numpy as np
print("Creating A 2D Array")
print("===================")
arr = np.arange(10).reshape(2,5)
print(arr)
print("===================")
print("Method-1")
print("--------")
print("Finding Mean of an Array")
print("========================")
print(arr.mean())
print("Method-2")
print("--------")
print("Finding Standard Deviation in an Array")
print("======================================")
print(arr.std())
print("Method-3")
print("--------")
print("Finding Variance in an Array")
print("============================")
print(arr.var())
print("Method-4")
print("--------")
print("Finding Transpose of an Array")
print("=============================")
print(arr.T)
print("Method-5")
print("--------")
print("Finding shape of an Array")
print("=========================")
print(arr.shape)
print("Method-6")
print("--------")
print("Finding dimension of an Array")
print("=============================")
print(arr.ndim)
print("Method-7")
print("--------")
print("Swapping axes an Array")
print("======================")
print(arr.swapaxes(1,0))
print("Method-8")
print("--------")
print("Finding Data Type of an Array")
print("=============================")
print(arr.dtype)
print("Method-9")
print("--------")
print("Finding A Percentile In An Array")
print("================================")
print(np.percentile(arr,2))
print("Method-10")
print("---------")
print("Rounding the Decimal Numbers In An Array")
print("========================================")
arr2 = np.array([10.03030,6.78782,8.76376])
print(np.around(arr2))
print("Method-11")
print("---------")
print("Finding Floor")
print("=============")
print(np.floor(arr2))
print("Method-12")
print("---------")
print("Finding Ceil")
print("============")
print(np.ceil(arr2))
print("Method-13")
print("---------")
print("Finding Truncated Value")
print("=======================")
print(np.trunc(arr2))
print("Method-14")
print("---------")
print("Finding Product Of An Array On A Particular Axes")
print("================================================")
print(np.prod(arr2,0))
print("Method-15")
print("---------")
print("Finding Sum Of An Array On A Particular Axes")
print("============================================")
print(np.sum(arr2,0))
print("Method-16")
print("---------")
print("Finding Comulative Sum Of An Array")
print("==================================")
print(np.cumsum(arr2))
print("Method-17")
print("---------")
print("Finding Comulaive Prodcut of an Array")
print("=====================================")
print(np.cumprod(arr2))
print("Method-18")
print("---------")
print("Finding N-th discrete Difference")
print("================================")
print(np.diff(arr))
print("Method-19")
print("---------")
print("Finding Gradient of An Array")
print("============================")
print(np.gradient(arr2))
print("Method-20")
print("---------")
print("Finding Exponential of the Elements of An Array")
print("===============================================")
print(np.exp(arr2))
print("Method-21")
print("---------")
print("Finding log-10 of an Array")
print("==========================")
print(np.log10(arr2))
print("Method-22")
print("---------")
print("Finding Reciprocal of an  Array")
print("===============================")
print(np.reciprocal(arr2))
print("Method-23")
print("---------")
print("Making Elements of An Array Numerical Positive")
print("==============================================")
print(np.positive(arr2))
print("Method-24")
print("---------")
print("Making Elements of An Array Numerical Negative")
print("==============================================")
print(np.negative(arr2))
print("Method-25")
print("---------")
print("Finding Absolute of An Array")
print("============================")
print(np.abs(arr2))
print("Method-26")
print("---------")
print("Finding The Square of the Elemnts of an Array")
print("=============================================")
print(np.square(arr2))
print("Method-27")
print("---------")
print("Finding Maximum of an Array")
print("===========================")
print(np.max(arr2))
print("Method-28")
print("---------")
print("Finding Minimum of an Array")
print("===========================")
print(np.min(arr2))
print("Method-29")
print("---------")
print("Finding Cube Root of the Elements of an Array")
print("=============================================")
print(np.cbrt(arr2))
print("Method-30")
print("---------")
print("Finding Element Wise Sign Indication of an Array")
print("================================================")
print(np.sign(arr2))
print("Method-31")
print("---------")
print("Finding Sine of A Value")
print("=======================")
print(np.sin(20))
print("Method-32")
print("---------")
print("Finding Cos of A Value")
print("======================")
print(np.cos(20))
print("Method-33")
print("---------")
print("Finding Tangent of A Value")
print("==========================")
print(np.tan(20))
print("Method-34")
print("---------")
print("Finding Hyperbolic Sine of an Array")
print("===================================")
print(np.sinh(arr2))
print("Method-35")
print("---------")
print("Finding Hyperbolic Cos of an Array")
print("==================================")
print(np.cosh(arr2))
print("Method-36")
print("---------")
print("Finding Hyperbolic Tangent of an Array")
print("======================================")
print(np.tanh(arr2))
print("Method-37")
print("---------")
print("Finding Inverse Hyperbolic Cosine of an Array")
print("=============================================")
print(np.arccosh(arr2))
print("Method-38")
print("---------")
print("Rounding a values of an array to the specific decimal place")
print("===========================================================")
print(np.around(arr2)[2])
print("Methos-39")
print("---------")
print("Rounding the values of an array to the nearest integer towards to zero")
print("======================================================================")
print(np.fix(arr2))
print("Method-40")
print("---------")
print("Rounding The Elements of an Array to the nearest integer")
print("========================================================")
print(np.rint(arr))
print("Method-41")
print("---------")
print("Finding Median of an Array")
print("==========================")
print(np.median(arr2))
print("Method-42")
print("---------")
print("Finding Mode of the Elements an Array")
print("=====================================")
print(np.mod(arr2,5))
print("Method-43")
print("---------")
print("Finding Dimension of an Array")
print("=============================")
print(arr2.ndim)
print("Method-44")
print("---------")
print("Finding shape of an Array")
print("=========================")
print(arr2.shape)
print("Method-45")
print("---------")
print("Inverting an Array")
print("==================")
print(np.invert(arr))
print("Method-46")
print("---------")
print("Finding Null Values in an Array")
print("===============================")
print(np.isnan(arr2))
print("Method-47")
print("---------")
print("Flattening an Array")
print("===================")
print(np.ravel(arr2))
print("Method-48")
print("---------")
print("Finding Square Root of an Array")
print("===============================")
print(np.sqrt(arr2))
print("Method-49")
print("---------")
print("sorting an Array")
print("================")
print(np.sort(arr2))
print("Method-50")
print("---------")
print("Creating a Zero Array of Desired Shape")
print("======================================")
print(np.zeros(20).reshape(5,4))